spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/ederwyk/spring-cloud-config-storage
                    username: ederwyk
                    password: ${GITHUB_TOKEN}
    application:
        name: config-server

server:
    port: 8888
